-- 체성분 기록 스키마. MEMBERS(MEMBER_ID) 테이블을 먼저 생성한 뒤 실행한다.
-- 회원 한 명은 같은 측정일에 체성분 기록을 1건만 가질 수 있다.
-- MVP에서는 잘못 기록한 경우 수정 대신 삭제 후 재등록한다.
-- 체중, 골격근량, 체지방률은 일부만 입력할 수 있다.
-- MEMBER_ID는 MEMBERS 테이블을 참조한다.

-- 체성분 기록 테이블
CREATE TABLE BODY_COMPOSITIONS (
    BODY_COMPOSITION_ID NUMBER(10) NOT NULL,
    MEMBER_ID NUMBER(10) NOT NULL,
    MEASURED_DATE DATE NOT NULL,
    WEIGHT NUMBER(5,2) NULL,
    SKELETAL_MUSCLE NUMBER(5,2) NULL,
    BODY_FAT_PERCENTAGE NUMBER(5,2) NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PK_BODY_COMPOSITIONS PRIMARY KEY (BODY_COMPOSITION_ID),
    CONSTRAINT FK_BC_MEMBER FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBERS (MEMBER_ID),
    CONSTRAINT UK_BC_MEMBER_DATE UNIQUE (MEMBER_ID, MEASURED_DATE),
    CONSTRAINT CK_BC_WEIGHT CHECK (WEIGHT IS NULL OR WEIGHT > 0),
    CONSTRAINT CK_BC_MUSCLE CHECK (SKELETAL_MUSCLE IS NULL OR SKELETAL_MUSCLE > 0),
    CONSTRAINT CK_BC_FAT CHECK (
        BODY_FAT_PERCENTAGE IS NULL OR BODY_FAT_PERCENTAGE BETWEEN 0 AND 100
    )
);

-- 체성분 PK 시퀀스
CREATE SEQUENCE SEQ_BODY_COMPOSITIONS
    START WITH 1
    INCREMENT BY 1
    NOCACHE;
